Online_store/apps/urls.py
from django.urls import path
from . import views

app_name = 'StoreApp'

urlpatterns = [
    path(r'', views.device, name = 'device'),
    path(r'<int:customer_id>', views.device, name = 'device'),
    path(r'device/<int:device_id>/<int:category>/<int:customer>/', views.criteria, name = 'device_criteria'),
    path(r'device/crit_all/<int:device_id>/<int:category>/<int:customer>/', views.criteria_all, name = 'criteria_all'),
    path(r'device/crit_no/<int:device_id>/<int:category>/<int:customer>/', views.criteria_no, name = 'criteria_no'),
    path(r'device/search/<int:category>/<int:customer>/', views.device_search, name = 'device_search'),
    path(r'device/comment_new/<int:device_id>/<int:category>/<int:customer>/', views.comment_new, name = 'comment_new'),
    path(r'category/<int:customer>/', views.category, name = 'category'),
    path(r'category/<str:category_name>_<int:category_id>/<int:customer>/', views.category_next, name = 'category_next'),
    path(r'customer/registration/<int:customer>/', views.customer_registration, name = 'customer_registration'),
    path(r'customer/registration/new/<int:customer>/', views.customer_new, name = 'customer_new'),
    path(r'customer/entry/<int:customer>/', views.customer_entry, name = 'customer_entry'),
    path(r'customer/entry/check/<int:customer>/', views.customer_entry_check, name = 'customer_entry_check'),
    path(r'customer/exit/', views.customer_exit, name = 'customer_exit'),
    path(r'customer/profile/<int:customer>/', views.customer_profile, name = 'customer_profile'),
    path(r'customer/profile/edit/<int:customer>/', views.customer_profile_edit, name = 'customer_profile_edit'),
    path(r'favorite/<int:customer>/', views.favorite_device, name = 'favorite_device'),
    path(r'basket/<int:customer>/', views.basket, name = 'basket'),
    path(r'basket/<int:device_id>/<int:customer>/', views.device_add_basket, name = 'device_add_basket'),
    path(r'favorite/clear/<int:customer>/', views.favorite_clear, name = 'favorite_clear'),
    path(r'basket/clear/<int:device_id>/<int:customer>', views.device_from_basket, name = 'device_from_basket'),
    path(r'category/clear/<int:customer>/', views.device_clear_category, name = 'device_clear_category'),
    path(r'filter/<int:customer>/', views.device_filter, name = 'filter'),
    path(r'filter/edit/<int:customer>/', views.device_edit_filter, name = 'edit_filter'),
    path(r'order_no/<int:customer>/', views.order_no, name = 'order_no'),
    path(r'order_begin/<int:customer>/', views.create_order, name = 'create_order'),
    path(r'order_next/<int:customer>/', views.order_next, name = 'order_next'),
    path(r'order_store/<int:customer>/<str:token>/', views.order_store, name = 'order_store'),
    path(r'order_finish/<int:customer>/<str:token>/', views.order_finish, name = 'order_finish'),
    path(r'order/<int:customer>/', views.order, name = 'order'),
    path(r'order_delete/<int:customer>/<int:order_number>/', views.order_delete, name = 'order_delete'),
    path(r'order_device/<int:customer>/<int:order_number>/', views.order_device, name = 'order_device')
]

Online_store/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('StoreApp.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Online_store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title> Онлайн-магазин электроники </title>
    <style type="text/css">
        h1 { text-align: center; }
        address { text-align: center; }
        main { min-height: 100%; margin-left: 20px; margin-top: 20px; padding-bottom: 40px; }
        body { height: 100%; }
        nav { margin-left: 20px; overflow: hidden; background-color: #333; font-family: Arial, Helvetica, sans-serif; }
        nav a { float: right; font-size: 16px; color: white; text-align: center; padding: 14px 16px; text-decoration: none; }
        nav a:hover { background-color: red; }
        show { display: block; }
        footer { text-align: center; width: 100%; height: 30px; margin: auto; clear: both; }
        #device_list { float: left; }
        #category_list { float: left; }
        #device_filter { float: left; }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
    <header>
        <h1> Онлайн-магазин электронных устройств </h1>
    </header>
    <hr>
    <nav>
        <a href = "{% url 'StoreApp:category' customer %}" id="category_list">Категории</a>
		<a href = "{% url 'StoreApp:device' customer %}" id="device_list">Устройства</a>
        <a href = "{% url 'StoreApp:filter' customer %}" id="device_filter">Фильтр устройств</a>
        {% if customer == 0 %}
        <a href = "{% url 'StoreApp:customer_registration' customer %}" id="registration">Регистрация</a>
        <a href = "{% url 'StoreApp:customer_entry' customer %}" id="entry">Войти</a>
        {% else %}
        <a href = "{% url 'StoreApp:customer_exit' %}" id="exit">Выйти</a>
        <a href = "{% url 'StoreApp:customer_profile' customer %}" id="profile">Профиль</a>
        <a href = "{% url 'StoreApp:basket' customer %}" id="basket">Корзина</a>
        <a href = "{% url 'StoreApp:favorite_device' customer %}" id="device_like">Просмотрено</a>
        <a href = "{% url 'StoreApp:order' customer %}" id="order_nav">Заказы</a>
        {% endif %}
    </nav>
    <hr>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <hr>
        <strong>Time: {% now "SHORT_DATETIME_FORMAT" %}</strong><br>
        <hr>
		<address>Шелаев Н. 3530901/80201. 2021г.</address>
	</footer>
</body>
</html>