Online_store/apps/urls.py
from django.urls import path
from . import views

app_name = 'StoreApp'

urlpatterns = [
    path(r'', views.device, name = 'device'),
    path(r'<int:customer_id>', views.device, name = 'device'),
    path(r'device/<int:device_id>/<int:category>/<int:customer>/', views.criteria, name = 'device_criteria'),
    path(r'device/crit_all/<int:device_id>/<int:category>/<int:customer>/', views.criteria_all, name = 'criteria_all'),
    path(r'device/crit_no/<int:device_id>/<int:category>/<int:customer>/', views.criteria_no, name = 'criteria_no'),
    path(r'device/search/<int:category>/<int:customer>/', views.device_search, name = 'device_search'),
    path(r'device/comment_new/<int:device_id>/<int:category>/<int:customer>/', views.comment_new, name = 'comment_new'),
    path(r'category/<int:customer>/', views.category, name = 'category'),
    path(r'category/<str:category_name>_<int:category_id>/<int:customer>/', views.category_next, name = 'category_next'),
    path(r'customer/registration/<int:customer>/', views.customer_registration, name = 'customer_registration'),
    path(r'customer/registration/new/<int:customer>/', views.customer_new, name = 'customer_new'),
    path(r'customer/entry/<int:customer>/', views.customer_entry, name = 'customer_entry'),
    path(r'customer/entry/check/<int:customer>/', views.customer_entry_check, name = 'customer_entry_check'),
    path(r'customer/exit/', views.customer_exit, name = 'customer_exit'),
    path(r'customer/profile/<int:customer>/', views.customer_profile, name = 'customer_profile'),
    path(r'customer/profile/edit/<int:customer>/', views.customer_profile_edit, name = 'customer_profile_edit'),
    path(r'favorite/<int:customer>/', views.favorite_device, name = 'favorite_device'),
    path(r'basket/<int:customer>/', views.basket, name = 'basket'),
    path(r'basket/<int:device_id>/<int:customer>/', views.device_add_basket, name = 'device_add_basket'),
    path(r'favorite/clear/<int:customer>/', views.favorite_clear, name = 'favorite_clear'),
    path(r'basket/clear/<int:device_id>/<int:customer>', views.device_from_basket, name = 'device_from_basket'),
    path(r'category/clear/<int:customer>/', views.device_clear_category, name = 'device_clear_category'),
    path(r'filter/<int:customer>/', views.device_filter, name = 'filter'),
    path(r'filter/edit/<int:customer>/', views.device_edit_filter, name = 'edit_filter'),
    path(r'order_no/<int:customer>/', views.order_no, name = 'order_no'),
    path(r'order_begin/<int:customer>/', views.create_order, name = 'create_order'),
    path(r'order_next/<int:customer>/', views.order_next, name = 'order_next'),
    path(r'order_store/<int:customer>/<str:token>/', views.order_store, name = 'order_store'),
    path(r'order_finish/<int:customer>/<str:token>/', views.order_finish, name = 'order_finish'),
    path(r'order/<int:customer>/', views.order, name = 'order'),
    path(r'order_delete/<int:customer>/<int:order_number>/', views.order_delete, name = 'order_delete'),
    path(r'order_device/<int:customer>/<int:order_number>/', views.order_device, name = 'order_device')
]

Online_store/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('StoreApp.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Online_store/templates/StoreApp/basket.html
{% extends 'base.html' %}
{% block style %}
<style>
    strong { margin-left: 20px; }
    radio { font-size: 18px; margin-top: 5px; }
    button { margin-top: 5px; margin-left: 20px; width: 200px; font-size: 18px; height: 30px; }
    form { text-align: left; }
    #device_delete { margin-left: 20px; color: crimson; }
    #flex-container { display: -webkit-flex; display: flex; -webkit-flex-direction: row; flex-direction: row; }
    #flex-container > .flex-item { -webkit-flex: auto; flex: auto; }
    #basket_class { display: inline-block; float: right; width: 50%; margin-left: 10px; vertical-align: top; }
    #order { display: inline-block; float: left; overflow: hidden; margin-left: 10px; vertical-align: top; }
    #device_choose { width: 30px; height: 30px; }
    #total { font-size: 25px; }
    #message { text-align: center; color: darkmagenta; font-size: 18px; }
    #office_set { margin-left: 20px; width: 450px; height: 30px; font-size: 18px; }
</style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong><br><br></div>
{% endif %}
<div id="flex-container">
<div class="content" id="basket_class">
    {% if list_basket %}
    {% if flag_order == 0 %}
    <ol>
        {% for basket in list_basket %}
        <li>
            <b>Когда? </b><i> {{basket.date_device_added}}</i><br>
            <b>Что? </b><i> {{basket.device}}</i><br>
            <b>Сколько? </b><i> {{basket.device_volume}}</i><br>
            <form action="{% url 'StoreApp:device_from_basket' basket.device.id customer %}" method="post" id="basket_delete">
                {% csrf_token %}
                <button type="submit" id="device_delete">Удалить из корзины</button>
            </form><br>
        </li>
        {% endfor %}
    </ol>
    <strong>Всего записей в корзине: {{list_basket|length}}</strong>
    {% elif flag_order == 1 %}
        <form action="{% url 'StoreApp:order_next' customer %}" method="post" id="basket_order_next">
        {% csrf_token %}
        <button type="submit" id="button_order_next">Подтвердить выбор</button><br><br>
        {% for basket in list_basket %}
            <b>Что? </b><i> {{basket.device}}</i><br>
            <b>Сколько? </b><i> {{basket.device_volume}}</i>
            <input type="checkbox" name="device_choose" id="device_choose" checked value="{{basket.basket_number}}"/><br><br>
        {% endfor %}
    </form>
    {% else %}
        <ol>
        {% for device in list_basket %}
        <li>
            <b>Что? </b><i> {{device.0.device_name}}</i><br>
            <b>Сколько? </b><i> {{device.1}}</i><br>
            <b>Цена за одно устройство: </b><i> {{device.0.price}} рублей </i><br><br>
        </li>
        {% endfor %}
    </ol>
    {% endif %}
    {% else %}
    <strong>Ваша Корзина пуста :(</strong> 
    {% endif %}
</div>
<div class="content" id="order">
    {% if list_basket|length > 0 %}
    {% if flag_order == 0 %}
    <form action="{% url 'StoreApp:create_order' customer %}" method="post" id="basket_order_begin">
         {% csrf_token %}
         <button type="submit" id="button_order_begin">Оформить заказ</button>
    </form>
    {% else %}
    <form action="{% url 'StoreApp:order_no' customer %}" method="post" id="basket_order_next">
        {% csrf_token %}
        <button type="submit" id="button_order_next">Отменить</button>
    </form><br>
    {% endif %}
    {% if flag_order == 2 %}
    <strong id="total">Общая цена: {{price}} рублей</strong><br><br>
     <form action="{% url 'StoreApp:order_store' customer token %}" method="post" id="office_choose">
        {% csrf_token %}
        <input type="radio" id="radio_1" value="1" name="order" checked/><label for="radio_1">Есть в наличии</label>
        <input type="radio" id="radio_2" value="2" name="order" /><label for="radio_2">Не важно</label><br><br>
        <button type="submit" id="button_office_choose">Выбрать магазин</button>
    </form>
    {% elif flag_order == 3 %}
    <strong id="total">Общая цена: {{price}} рублей</strong><br><br>
    <form action="{% url 'StoreApp:order_finish' customer token %}" method="post" id="order_finish">
        {% csrf_token %}
        <input type="text" required placeholder="Магазин" id="office_set" name="office_set" list="datalist_office" value="ANY?"/><br>
        <datalist id="datalist_office">
        {% for office in list_store %}
        <option value="{{office.city}}|{{office.street}}|{{office.store_number}}">
        {% endfor %}
        <option value="ANY?">
        </datalist>
        <br><input type="radio" id="radio_3" value="1" name="courier" checked/><label for="radio_3">Самовывоз</label>
        <input type="radio" id="radio_4" value="2" name="courier" /><label for="radio_4">Курьер</label><br><br>
        <button type="submit" id="button_order_finish">Подтвердить заказ</button>
    </form>
    {% endif %}
    {% endif %}
</div>
</div>
{% endblock %}

Online_store/templates/StoreApp/customer_entry.html
{% extends 'base.html' %}
{% block style %}
    <style>
        input { font-size: 18px; margin-top: 5px; }
        #form_entry { text-align: center; }
        #customer_entry { width: 150px; height: 35px; font-size: medium; }
        #message { text-align: center; color: red; font-size: 18px; margin-bottom: 5px; }
    </style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong></div>
{% endif %}
<form action="{% url 'StoreApp:customer_entry_check' customer %}" method="post" autocomplete="on" id="form_entry">
    {% csrf_token %}
    <input type="text" required placeholder="Login" name="login" /><br>
    <input type="password" required placeholder="Password" name="password" /><br><br>
    <button type="submit" id="customer_entry">Entry?</button><br>
</form>
{% endblock %}

Online_store/templates/StoreApp/customer_profile.html
{% extends 'base.html' %}
{% block style %}
    <style>
        label { font-size: 20px; }
        input { font-size: 18px; margin-top: 5px;}
        i { font-size: 20px; }
        #form_profile { text-align: center; }
        #customer_profile { width: 200px; height: 40px; font-size: medium; }
        #date_birth { width: 155px; }
        #message { text-align: center; color: red; font-size: 18px; }
    </style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong></div>
{% endif %}
<form action="{% url 'StoreApp:customer_profile_edit' profile.id %}" method="post" autocomplete="on" id="form_profile">
    {% csrf_token %}
    <input type="text" required placeholder="Login" name="login" value="{{profile.login}}"/><br>
    <input type="password" placeholder="Password" name="password" id="password"/><br>
    <input type="password" placeholder="Password (again)" name="password_again" /><br>
    <input type="text" required placeholder="Name" name="first_name" value="{{profile.first_name}}"/><br>
    <input type="text" required placeholder="Surname" name="second_name" value="{{profile.second_name}}"/><br>
    <i>Gender: </i>
    <input type="radio" id="radio_1" value="O" name="gender" checked/><label for="radio_1">{{profile.gender}}</label>
    <input type="radio" id="radio_2" value="N" name="gender" /><label for="radio_2">Other?</label><br>
    <i>Date of Birth: {{profile.date_of_birth}}</i><br>
    <i>Modify? </i><input type="date" id="date_birth" placeholder="Date of Birth" name="date_of_birth"/><br>
    <input type="tel" required placeholder="Phone" name="phone" pattern="^\+?\d{1,3}-[(]\d{3}[)]-\d{3}-\d{4}$" value="{{profile.phone}}"/><br>
    <input type="email" required placeholder="Email" name="email" value="{{profile.email}}"/><br><br>
    <button type="submit" id="customer_profile">Accept changes?</button><br>
</form>
{% endblock %}

Online_store/templates/StoreApp/customer_registration.html
{% extends 'base.html' %}
{% block style %}
    <style>
        label { font-size: 20px; }
        input { font-size: 18px; margin-top: 5px;}
        i { font-size: 20px; }
        #form_registration { text-align: center; }
        #customer_registration { width: 200px; height: 40px; font-size: medium; }
        #date_birth { width: 155px; }
        #message { text-align: center; color: red; font-size: 18px; }
    </style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong></div>
{% endif %}
<form action="{% url 'StoreApp:customer_new' customer %}" method="post" autocomplete="on" id="form_registration">
    {% csrf_token %}
    <input type="text" required placeholder="Login" name="login" /><br>
    <input type="password" required placeholder="Password" name="password" /><br>
    <input type="password" required placeholder="Password (again)" name="password_again" /><br>
    <input type="text" required placeholder="Name" name="first_name" /><br>
    <input type="text" required placeholder="Surname" name="second_name" /><br>
    <i>Gender: </i>
    <input type="radio" id="radio_1" value="M" name="gender" checked/><label for="radio_1">Male</label>
    <input type="radio" id="radio_2" value="F" name="gender" /><label for="radio_2">Female</label><br>
    <i>Date of Birth: </i><input type="date" id="date_birth" required placeholder="Date of Birth" name="date_of_birth" /><br>
    <input type="tel" required placeholder="Phone" name="phone" pattern="^\+?\d{1,3}-[(]\d{3}[)]-\d{3}-\d{4}$"/><br>
    <input type="email" required placeholder="Email" name="email" /><br><br>
    <button type="submit" id="customer_registration">Ready to register?</button><br>
</form>
{% endblock %}

Online_store/templates/StoreApp/device.html
{% extends 'base.html' %}
{% block style %}
<style type="text/css">
    input { font-size: 18px; margin-top: 5px; }
    strong { margin-left: 20px; }
    #device_size { width: 300px; font-size: 16px; }
    #device_search { width: 308px; font-size: 16px; }
    #device_button { margin-top: 5px; width: 140px; height: 35px; font-size: medium; }
    #device { color: darkblue; text-decoration: none; }
    #message { text-align: center; color: darkmagenta; font-size: 18px; }
    #search { margin-left: 20px; }
    #price_min_output { width: 70px; }
    #price_max_output { width: 70px; }
    #clear_category { margin-top: 5px; margin-left: 20px; width: 200px; font-size: 18px; height: 30px; }
</style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong></div>
{% endif %}
    <form action="{% url 'StoreApp:device_search' category customer %}" method="post" autocomplete="on" id="search">
            {% csrf_token %}
            <input type="number" placeholder="Количество отображаемых устройств" id="device_size" name="size" min="1" max="1000"/><br>
            <input type="search" placeholder="Поиск устойств по названию" id="device_search" name="device_search"/><br>
            Минимальная цена: <input type="range" id="price_min" required name="price_min" min="100" max="150000" value="1500" step="1000">
            <input type="text" id="price_min_output"><br>
            Максимальная цена:<input type="range" id="price_max" required name="price_max" min="100" max="150000" value="100000" step="1000">
            <input type="text" id="price_max_output"><br>
            <input type="radio" id="radio_1" value="1" name="order" checked/><label for="radio_1">Увеличение стоимости</label>
            <input type="radio" id="radio_2" value="2" name="order" /><label for="radio_2">Уменьшение стоимости</label><br>
            <button type="submit" id="device_button">Применить</button>
            <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
            <script id="rendered-js-2" >
                $(document).ready(function () {
                    $('#price_min_output').val($('#price_min').val());
                    $('#price_min').mousemove(function () { $('#price_min_output').val($('#price_min').val()); });
                    $('#price_min_output').change(function () { $('#price_min').val($('#price_min_output').val()); });
                });
            </script>
            <script id="rendered-js-3" >
                $(document).ready(function () {
                    $('#price_max_output').val($('#price_max').val());
                    $('#price_max').mousemove(function () { $('#price_max_output').val($('#price_max').val()); });
                    $('#price_max_output').change(function () { $('#price_max').val($('#price_max_output').val()); });
                });
            </script>
    </form>
    {% if category > 0 %}
            <form action="{% url 'StoreApp:device_clear_category' customer %}" method="post" id="clear_category">
                {% csrf_token %}
                <button type="submit" id="device_clear_category">Сбросить категорию</button>
            </form>
    {% endif %}
    {% if list_device %}
        <ol>
        {% for device in list_device %}
            <li><a href="{% url 'StoreApp:device_criteria' device.id category customer %}" id="device">
                {{device.device_name}} || {{device.price}} руб</a><br></li>
        {% endfor %}
        </ol>
        <strong>Всего найдено устройств: {{list_device|length}}</strong>
    {% else %}
        <br><strong>Устройства не найдены :( Повторите попытку с другими данными!</strong>
    {% endif %}
{% endblock %}

Online_store/templates/StoreApp/device_category.html
{% extends 'base.html' %}
{% block style %}
<style>
    strong { margin-left: 20px; }
    #category { color: midnightblue; text-decoration: none; text-transform: capitalize; }
</style>
{% endblock %}
{% block content %}
    {% if list_category %}
    <ul>
        {% for category in list_category %}
            <li><a href="{% url 'StoreApp:category_next' category.category_name category.id customer %}" id="category">
                {{category.category_name}}</a><br></li>
        {% endfor %}
    </ul>
    {% else %}
        <strong>Категории не найдены :( Повторите попытку позже!</strong>
    {% endif %}
{% endblock %}

Online_store/templates/StoreApp/device_criteria.html
{% extends 'base.html' %}
{% block style %}
<style>
    h2 { text-align: center; }
    #flex-container { display: -webkit-flex; display: flex; -webkit-flex-direction: row; flex-direction: row; }
    #flex-container > .flex-item { -webkit-flex: auto; flex: auto; }
    #comment { display: inline-block; float: right; width: 50%; margin-left: 10px; vertical-align: top; }
    #device { display: inline-block; float: left; overflow: hidden; margin-left: 10px; vertical-align: top; }
    #output { width: 20px; }
    #comment_new { margin-left: 25px; } 
    #comment_button { width: 180px; height: 30px; }
    #message { text-align: center; color: darkmagenta; font-size: 18px; }
    #list_comment { margin-left: 25px; }
    #feedback { margin-left: 15px; }
    #basket { margin-left: 20px; }
    #basket_size { width: 100px; height: 25px; font-size: 16px; }
    #device_button { width: 180px; height: 30px; color: crimson; font-size: 16px; }
    #all { margin-left: 30px; }
    #device_image { margin-left: 10px; height: 200px; width: 95px; }
    #crit_button { width: 250px; height: 40px; font-size: 18px; }
    #crit_no_button { width: 250px; height: 40px; font-size: 18px; }
</style>
{% endblock %}
{% block content %}
<h2>{{device.device_name}}</h2>
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong><br><br></div>
{% endif %}
{% if customer > 0 %}
<div id="flex-container">
<div class="content" id="device">
    <form action="{% url 'StoreApp:device_add_basket' device.id customer %}" method="post" autocomplete="on" id="basket">
        {% csrf_token %}
        <input type="number" placeholder="Сколько?" id="basket_size" name="basket_size" min="1" max="25"/>
        <button type="submit" id="device_button">Добавить в корзину</button>
    </form><br>
{% endif %}
<table>
    <colgroup><col span="2" style="background-color: whitesmoke"></colgroup>
    <tr>
        <td>Цена: </td>
        <td>{{device.price}} рублей</td>
    </tr>
    <tr>
        <td>Рейтинг: </td>
        <td>{{device.rating}}</td>
    </tr>
    <tr>
        <td>Компания: </td>
        <td>
            {% if device.company is not None %}
                {{device.company}}
            {% else %}
                Неизвестно
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>Гарантия: </td>
        <td>{{device.warranty}} месяцев</td>
    </tr>
    <tr>
        <td>Год выпуска: </td>
        <td>{{device.release_year}}</td>
    </tr>
    <tr>
        <td>Высота: </td>
        <td>{{device.height}} мм</td>
    </tr>
    <tr>
        <td>Ширина: </td>
        <td>{{device.width}} мм</td>
    </tr>
    <tr>
        <td>Толщина: </td>
        <td>{{device.thickness}} мм</td>
    </tr>
    <tr>
        <td>Вес: </td>
        <td>{{device.weight}} гр</td>
    </tr>
    <tr>
        <td>Цвет: </td>
        <td>{{device.colour}}</td>
    </tr>
    <tr>
        <td>Материал: </td>
        <td>{{device.material}}</td>
    </tr>
    {% if device.screen_size is not None %}
    <tr>
        <td>Размер экрана: </td>
        <td>{{device.screen_size}}</td>
    </tr>
    {% endif %}
    {% if device.processor is not None %}
    <tr>
        <td>Процессор: </td>
        <td>{{device.processor}}</td>
    </tr>
    {% endif %}
    {% if device.battery_capacity is not None %}
    <tr>
        <td>Емкость батареи/аккумулятора: </td>
        <td>{{device.battery_capacity}}</td>
    </tr>
    {% endif %}
    {% if list_criteria %}
    <tr></tr>
    {% for row in list_criteria %}
    <tr>
        <td>{{row.0}}</td>
        <td>{{row.1}}</td>
    </tr>
    {% endfor %}{% endif %}
</table>
{% if not flag %}
<form action="{% url 'StoreApp:criteria_all' device.id category customer %}" method="post" id="criteria_all">
            {% csrf_token %}
            <br><button type="submit" id="crit_button">Больше характеристик</button>
</form>
{% else %}
<form action="{% url 'StoreApp:criteria_no' device.id category customer %}" method="post" id="criteria_no">
            {% csrf_token %}
            <br><button type="submit" id="crit_no_button">Меньше характеристик</button>
</form>
{% endif %}
</div>
<div class="content" id="comment">
    {% if list_image %}
        <p>{% for image in list_image %}
            <img src="{{image}}" id="device_image" loading="lazy" align="middle" alt="Device image">
        {% endfor %}
        </p><br>
    {% else %}
        <strong>Картинки не найдены! :(</strong><br>
    {% endif %}
    {% if customer > 0 %}
    <form action="{% url 'StoreApp:comment_new' device.id category customer %}" method="post" id="comment_new">
            {% csrf_token %}
            Рейтинг:<br><input type="range" id="rating" required name="rating" min="0.1" max="5.0" value="2.5" step="0.1">
            <input type="text" id="output"><br>
            Комментарий:<br><textarea name="comment" cols="30" rows="3" placeholder="Это необязательно"></textarea><br>
            <button type="submit" id="comment_button">Оставить комментарий</button>
            <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
            <script id="rendered-js-1" >
                $(document).ready(function () {
                    $('#output').val($('#rating').val());
                    $('#rating').mousemove(function () { $('#output').val($('#rating').val()); });
                    $('#output').change(function () { $('#rating').val($('#output').val()); });
                });
            </script>
    </form>
    {% endif %}
    {% if list_comment %}
        <ol>
        {% for comment in list_comment %}
            <li>
            <b>Кто? {{comment.customer}}</b><br>
            <b>Когда? {{comment.date_of_feedback}}</b><br>
            <b>Рейтинг: {{comment.rating_of_device}}</b><br>
            {% if comment.comment_feedback is not None %}
                <i id="feedback">Отзыв: {{comment.comment_feedback}}</i><br>
            {% endif %}
            <br></li>
        {% endfor %}
        </ol>
        <strong id="all">Всего комментариев: {{list_comment|length}}</strong>
    {% else %}
        <br><strong id="fail">Комментарии не найдены :( Станьте первыми!</strong>
    {% endif %}
</div>
</div>
{% endblock %}

Online_store/templates/StoreApp/favorite_device.html
{% extends 'base.html' %}
{% block style %}
<style>
    strong { margin-left: 20px; }
    #favorite_device { color: midnightblue; text-decoration: none; }
    #clear { margin-left: 50px; height: 40px; width: 200px; font-size: 20px; color: firebrick; }
</style>
{% endblock %}
{% block content %}
    {% if list_favorite %}
    <form action="{% url 'StoreApp:favorite_clear' customer %}" method="post" id="favorite_clear">
        {% csrf_token %}
        <button type="submit" id="clear">Очистить список</button>
    </form><br>
    <ul>
        {% for favorite in list_favorite %}
            <li><a href="{% url 'StoreApp:device_criteria' favorite.device.id 0 customer %}" id="device">
                {{favorite.date_last_view}}: {{favorite.device}}</a><br></li>
        {% endfor %}
    </ul>
    <strong>Всего устройств: {{list_favorite|length}}</strong>
    {% else %}
        <strong>Список просмотренных устройств пуст :(</strong>
    {% endif %}
{% endblock %}

Online_store/templates/StoreApp/order.html
{% extends 'base.html' %}
{% block style %}
<style>
    button { margin-top: 5px; margin-left: 20px; width: 200px; font-size: 18px; height: 30px; }
    #message { text-align: center; color: darkmagenta; font-size: 18px; }
    #flex-container { display: -webkit-flex; display: flex; -webkit-flex-direction: row; flex-direction: row; }
    #flex-container > .flex-item { -webkit-flex: auto; flex: auto; }
    #info { display: inline-block; float: right; width: 50%; margin-left: 10px; vertical-align: top; }
    #order { display: inline-block; float: left; overflow: hidden; margin-left: 10px; vertical-align: top; }
    #total { font-size: 25px; margin-left: 50px; }
</style>
{% endblock %}
{% block content %}
{% if message != '' %}
    <div id="message" class="content"><strong>{{message}}</strong><br><br></div>
{% endif %}
{% if list_order %}
<div id="flex-container">
<div class="content" id="order">
{% if list_order %}
<ol>
    {% for order in list_order %}
    <li>
        <b>Когда сделан заказ? {{order.date_of_purchase}}</b><br>
        <b>Номер заказа: {{order.order_number}}</b><br>
        <b>Магазин: {{order.office.city}}, {{order.office.street}}, {{order.office.house_number}} | {{order.office}}</b><br>
        <b>Когда будет готов заказ? {{order.date_of_delivery}}</b><br>
        <b>Статус заказа: {{order.order_flag}}</b><br>
        <form action="{% url 'StoreApp:order_device' customer order.order_number %}" method="post" id="order_device">
            {% csrf_token %}
            <button type="submit" id="button_device">Показать устройства</button>
        </form>
        <form action="{% url 'StoreApp:order_delete' customer order.order_number %}" method="post" id="order_delete">
            {% csrf_token %}
            <button type="submit" id="button_delete">Отменить заказ</button>
        </form>
        <br>
    </li>
    {% endfor %}
</ol>
<strong id="all">Всего заказов: {{list_order|length}}</strong>
{% else %}
<br><strong id="fail">У вас ещё нет заказов :(</strong>
{% endif %}
</div>
<div class="content" id="info">
    {% if list_device.0 %}
    <strong id="total">Общая цена: {{list_device.1}} рублей</strong><br>
     <ol>
        {% for device in list_device.0 %}
        <li>
            <b>Что? </b><i> {{device.device}}</i><br>
            <b>Сколько? </b><i> {{device.device_count}}</i><br>
            <b>Цена за одно устройство: </b><i> {{device.device_price}} рублей </i><br><br>
        </li>
        {% endfor %}
    </ol>
    {% endif %}
</div>
</div>
{% endif %}
{% endblock %}